### ISSUE TITLE
Shouldn't some of these values be counters?

### ISSUE THREAD

**Issue by gphat** [ianks/yabeda-gc#7]
Hello! Thanks for your work! I noticed today that all of these metrics are registered as gauges, but many (time, minor_gc_count, major_gc_count) seem to be counters. Am I missing something about these metrics?

For example, `minor_gc_count` is "The total number of minor garbage collections run since process start."

**Comment by Envek** [comment]
Hey! Yes, ideally they should be counters. The problem is that we can't get access to underlying events to increment counters ourselves, we can only “observe” their current value. That's why they are gauges.

It is possible to complicate current implementation (e.g. on every observation calculate delta with last observed value and increment the counter with it), but as (I believe) in most of monitoring systems you can treat every metric as a counter, it doesn't seem to worth it IMO.

**Comment by gphat** [comment]
ahhh, of coruse. you don't know what to `increment` by! Welp, that sounds like a dumb question on my part now but you don't know until you ask. Thanks!
